//parking area action types
export const ADD_PARKING_AREA = 'ADD_PARKING_AREA';

export const FETCH_PARKING_AREAS_START = 'FETCH_PARKING_AREAS_START';
export const FETCH_PARKING_AREAS_FAILED = 'FETCH_PARKING_AREAS_FAILED';
export const FETCH_PARKING_AREAS_SUCCESS = 'FETCH_PARKING_AREAS_SUCCESS';
export const FETCH_PARKING_AREAS_SAGA = 'FETCH_PARKING_AREAS_SAGA';
export const FETCH_PARKING_AREAS_BY_NAME_SAGA = 'FETCH_PARKING_AREAS_BY_NAME_SAGA';  
export const FETCH_PARKING_AREAS_BY_NAME_SUCCESS = 'FETCH_PARKING_AREAS_BY_NAME_SUCCESS';  

export const FETCH_PARKING_SPOTS_START = 'FETCH_PARKING_SPOTS_START';
export const FETCH_PARKING_SPOTS_FAILED = 'FETCH_PARKING_SPOTS_FAILED';
export const FETCH_PARKING_SPOTS_SUCCESS = 'FETCH_PARKING_SPOTS_SUCCESS'
export const FETCH_PARKING_SPOTS_SAGA = 'FETCH_PARKING_SPOTS_SAGA';
export const FETCH_PARKING_SPOTS_BY_PARKING_NAME_START = 'FETCH_PARKING_SPOTS_BY_PARKING_NAME_START';
export const FETCH_PARKING_SPOTS_BY_PARKING_NAME_SUCCESS = 'FETCH_PARKING_SPOTS_BY_PARKING_NAME_SUCCESS';
export const FETCH_PARKING_SPOTS_BY_PARKING_NAME_SAGA= 'FETCH_PARKING_SPOTS_BY_PARKING_NAME_SAGA';
// export const FETCH_PARKING_SPOTS_BY_PARKING_NAME= 'FETCH_PARKING_SPOTS_BY_PARKING_NAME';

export const REMOVE_PARKING_AREA = 'REMOVE_PARKING_AREA';
